print("###############################")
print("#                             #")
print("#   M Izzuddin Abdis Salam    #")
print("#       2210817110005         #")
print("#                             #")
print("###############################")